### PR TITLE
Allow reading profiler output directly from a URL

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by edquist** [comment]
Hey @matyasselmeci,

Presumably you're interested in my feedback on the changes to `osg-installed-versions` in your ab9c9cac16134ca4cbbecc79fd640e5b0ab235bc (and not the `osg-system-profiler-viewer` changes from 8d6a841c599301f69ba92de28a4ff7f358a898ef).

I think I'd rather keep the logic simpler in `osg-installed-versions` and just allow specifying a URL for the PATH arguments.  Eg, 87ad1866a2716325658fde593c079776a0ba948c / https://github.com/opensciencegrid/osg-system-profiler/compare/master...edquist:url-paths.   And then `osg-system-profiler-viewer` should work unmodified.  Can you see if that works for you, and if so reset your PR (to 87ad1866a2716325658fde593c079776a0ba948c) ?

(As for the regex change you slipped in [here](https://github.com/opensciencegrid/osg-system-profiler/pull/1/commits/ab9c9cac16134ca4cbbecc79fd640e5b0ab235bc#diff-258798b6abde1e9d7c0e8ae6f47d2a49R36), I'm guessing it can probably go in a separate commit.)

**Comment by matyasselmeci** [comment]
Sure. Um, where does 87ad186 live? The Github URL suggests it's in opensciencegrid's repo, but I don't get it if I fetch. How did you create it in the first place?

**Comment by edquist** [comment]
It's in my edquist:url-paths branch, but apparently github shares commits between forks; sorry for the confusion.

You can fetch it with
`git fetch https://github.com/edquist/osg-system-profiler url-paths`
and then your `FETCH_HEAD` will point to my url-paths branch / 87ad186.

**Comment by matyasselmeci** [comment]
We'll use Carl's version instead of this.

**Pull request closed without merging**
